// Generated by https://quicktype.io

export interface HeartBeatsPayload {
  data: Datum[];
  end: string;
  start: string;
  timezone: string;
}

export interface Datum {
  entity: string;
  type: string;
  category: string;
  browser: string;
  domain: string;
  path: string;
  // branch: string;
  // created_at: string;
  // cursorpos: null;
  // dependencies: string;
  // id: string;
  // is_write: boolean;
  // language: string;
  // lineno: null;
  // lines: number;
  // machine_name_id: string;
  // project: string;
  user_agent: string;
  time: Date;
  // type: string;
  // user_id: string;
}

export interface SendHeartbeat {
  // branch: string | null;
  // hostname: string;
  // project: string | null;
  // url: string;
  // entity: string;
  // type: string;
  // category: string;
  browser: string; // which browser is being used
  domain: string; // domain of current page
  path: string; // path of current page
  user_agent: string; // user agent of current browser
  time: Date;
}

export interface ProjectDetails {
  category: string;
  editor: string;
  language: string;
  project: string;
}

export interface PostHeartbeatMessage {
  projectDetails?: ProjectDetails;
  recordHeartbeat: boolean;
}
